version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    # nur sichere/kleinere Updates, wenn du magst:
    # allow:
    #   - dependency-type: "all"
    labels:
      - "dependencies"
    rebase-strategy: "auto"
