site_name: "{{ username }}.github.io"
site_url: "https://{{ username }}.github.io"
repo_url: "https://github.com/{{ username }}/{{ repo_name }}"
repo_name: !ENV GITHUB_REPOSITORY
theme:
  name: material
  logo: assets/images/plex-logo.webp
  custom_dir: docs/overrides
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.footer
    - navigation.indexes
    - navigation.tracking
    - navigation.top
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: de
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple

nav:
  - Intro: index.md
  - Was ist Plex?: what-is-plex.md
  - Ist Plex sicher?: plex-safety.md
    - Empfohlene Datenschutzeinstellungen: recommended_datenprotectionsettings.md
  - Newsletter-Abonnements verwalten: unsubscribe-from-plex-newsletter.md
  - Bibliotheken anheften: pinning-libraries.md
  - Deaktivieren von Online-Medienquellen: disabling-online-media-sources.md
  - Content-Qualität und Aktualisierungsprozess: special-requests.md
  - Ändern der Plex-Streaming-Qualität:
    - changing-stream-quality/index.md
    - iOS & Android: changing-stream-quality/ios-android.md
    - tvOS (Apple TV): changing-stream-quality/tv-os.md
    - Amazon Fire TV, Android TV, PlayStation, Xbox, Roku, Smart TV (LG, Samsung, VIZIO): changing-stream-quality/streaming-devices.md
    - Webbrowser: changing-stream-quality/web-browser.md
 ## - FAQ:
   ## - What is transcoding?: faq/what-is-transcoding.md
   ## - My video won't stop buffering: faq/wont-stop-buffering.md
   ## - I requested something an hour ago but it hasn't shown up yet. Why?: faq/missing-requests.md
   ## - I'm having a problem with a Movie or TV Show: faq/content-issues.md

plugins:
  - search
  - markdownextradata: {}
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - git-committers:
      repository: !ENV GITHUB_REPOSITORY
      branch: !ENV GITHUB_REF_NAME
      exclude_committers:
        - "web-flow"  # GitHub web UI edits
        - "actions-user"  # GitHub Actions
        - "github-actions[bot]"  # GitHub Actions bot
      # For a repository hosted on GitHub, you can provide a token to increase the rate limit and go beyond the default 60 requests per hour per IP address.
      # The plugin will make one request per mkdocs document
      # See: https://github.com/ojacques/mkdocs-git-committers-plugin-2
      token: !ENV GITHUB_TOKEN

markdown_extensions:
  - toc:
      toc_depth: 1
      permalink: true
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: "Copyright &copy; 2026 {{ username }}"

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/solid/globe
      link: "https://{{ username }}.github.io/mkdocs-plex-guide-template/"
      name: Personal Website

  vars:
    username: !ENV GITHUB_REPOSITORY_OWNER
    repo_name: !ENV GITHUB_REPOSITORY
    request_url: "request.example.com"
    plex_url: "plex.example.com"
    plex_libraries: "Movies, Movies (Kids) und TV"
    noreply_email: "noreply@example.com"

  env:
    branch: !ENV [GITHUB_REF_NAME, 'main']
    commit_sha: !ENV [commit_sha, '']  # Will be empty on main, show SHA on develop
